pub mod audio;
pub mod database;
pub mod dedup;
pub mod licensing;
pub mod live_minutes;
pub mod model_manager;
pub mod summarization;
pub mod template_store;
pub mod templates;
pub mod vad;

#[cfg(target_os = "macos")]
pub mod audio_capture;
#[cfg(target_os = "macos")]
pub mod voice_capture;
#[cfg(target_os = "macos")]
pub mod permissions;
#[cfg(target_os = "macos")]
pub mod meeting_detector;
#[cfg(target_os = "macos")]
pub mod transcription;
